#include "./relat.h"

/* POTCUL_NSPH: calculates non spherical coulomb potential and energy
		from non spherical azimuthal symmetric density
 INPUT:
  **Rho		The density
  *cos_theta	The angular grid as generated by gauleg
  *weights	The weights as generated by gauleg
  maxlexp	Order of expansion in legendre polinoms
  *r		Radial grid
  drdi		dr(i)/di  [=r[i]*h in the log-mesh case]
 OUTPUT:
  **Vc		Non spherical coul-potential, nuclear potential included
 RETURN
  enee		Electron-electron coulomb energy 
*/

double potcul_nsph( Grid2d Rho, Grid2d Vc,
		    double *cos_theta, double *weights,
		    double *r, double *vnuc, double *drdi, int maxlexp)
{
  register int i,n;
  int l, il;
  double temp, **rhotr, **vctr, **vctrp, **lp, enee, rn, vlen;
  double *integrand;
/*   char filename[128]; */
/*   FILE *fp; */

  integrand = vector_alloc(nrmax);

  rhotr = matrix_alloc( 1+maxlexp/2, nrmax);
  vctr  = matrix_alloc( 1+maxlexp/2, nrmax);
  vctrp = matrix_alloc( 1+maxlexp/2, nrmax);
  lp    = matrix_alloc( 1+maxlexp/2, nlmax);

  /* find legendre components of Rho storing them in rhotr */
  for( l=0; l<=maxlexp; l+=2) {/* only even components are in Rho */
    il = l/2;
    for( i=0; i<nlmax; i++)
      lp[il][i] = LegPol( l, 0, cos_theta[i]);

    for( n=0; n<nrmax; n++)
    {
      for( temp=i=0; i<nlmax; i++)
	temp += weights[i] * lp[il][i] * Rho[i][n];
      rhotr[il][n] = (l+.5)*temp * M_4PI;
    }
  }

  for( i=0; i<nlmax; i++)
    for( n=0; n<nrmax; n++)
      Vc[i][n] = vnuc[n]; /* Ryd. */
  for( l=0; l<=maxlexp; l+=2) /* only even components are in Vc */
  {
    il = l/2;
    nsphint( vctr[il], vctrp[il], rhotr[il], r, drdi, l); 
    for( i=0; i<nlmax; i++)
      for( n=0; n<nrmax; n++)
	Vc[i][n] += vctr[il][n] * lp[il][i] * 2.0; /* Ryd. */
  }    

  for( enee=l=0; l<=maxlexp; l+=2) {
    il = l/2;
    for( n=0; n<nrmax; n++) {
      rn = r[n];
      integrand[n] = vctr[il][n] *  rhotr[il][n] *rn*rn * drdi[n];
    }
/*  Integrate and add the contribution from 0 to r0 */
    vlen = (simpson(integrand, nrmax, 1.0))/(2*l+1); /* Ryd. */
    printf("Tot energy contrib. from Leg. coul-potential component #%d: %14.8lg Ry\n", 
            l, vlen);
    enee += vlen;
  }  

/*   for( l=0; l<=maxlexp; l+=2) */
/*     { */
/*       sprintf( filename, "RHOTR%02d", l); */
/*       fp = fopen( filename, "w"); */
/*       for( n=0; n<nrmax; n++) */
/* 	{ */
/* 	  fprintf( fp, "%lg %lg %lg\n", */
/* 		   r[n], M_4PI/(2.*l+1.)*rhotr[l/2][n], vctr[l/2][n]); */
/* 	} */
/*       fclose(fp); */
/*     }  */

  matrix_free( rhotr,  1+maxlexp/2, nrmax);
  matrix_free(  vctr,  1+maxlexp/2, nrmax);
  matrix_free( vctrp,  1+maxlexp/2, nrmax);
  matrix_free(    lp,  1+maxlexp/2, nlmax);

  vector_free(integrand);

  return enee;
}
